version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - webnet

  php:
    image: php:7.4-fpm
    container_name: php_server
    volumes:
      - ./app:/var/www/html
    networks:
      - webnet
    environment:
      - MYSQLI_ALLOW_LOCAL_INFILE=On
    command: /bin/sh -c "docker-php-ext-install mysqli && docker-php-entrypoint php-fpm"

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foro_db
      MYSQL_USER: foro_user
      MYSQL_PASSWORD: foropassword
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - webnet

networks:
  webnet:
    name: webnet
